name: Build Typewriter Plugin

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Plugin
        uses: ./.github/actions/build-plugin
      - name: Upload Plugin
        uses: actions/upload-artifact@v2
        with:
          name: typewriter.jar
          path: plugin/build/libs/typewriter.jar
