name: Build Development Jars and Publish

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'plugins/**'
      - 'adapters/**'
      - '.github/workflows/build-development-jars-and-publish.yml'
  
jobs:
  build-publish-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Get version
        id: vars
        run: |
          version=$(cat version.txt)
          short_sha=$(echo $GITHUB_SHA | cut -c1-7)
          full_version="${version}-dev-${short_sha}"
          echo $full_version > version.txt
          echo "version=$full_version" >> $GITHUB_OUTPUT
      - name: Build Plugin
        uses: ./.github/actions/build-plugin
      - name: Build Basic Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: BasicAdapter
      - name: Build Citizens Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: CitizensAdapter
      - name: Build CombatLogX Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: CombatLogXAdapter
      - name: Build MythicMobs Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: MythicMobsAdapter
      - name: Build RPGRegions Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: RPGRegionsAdapter
      - name: Build SuperiorSkyblock Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: SuperiorSkyblockAdapter
      - name: Build Vault Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: VaultAdapter
      - name: Build WorldGuard Adapter
        uses: ./.github/actions/build-adapter
        with:
          adapter: WorldGuardAdapter
      - name: Publish Development Jars
        uses: Kir-Antipov/mc-publish@v3.3
        id: publish
        with:
          modrinth-id: "Vm7B3ymm"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: false
          files: |
            plugin/build/libs/typewriter.jar
            adapters/**/build/libs/*.jar
          name: "Typewriter v${{ steps.vars.outputs.version }} Development Build"
          version: "${{ steps.vars.outputs.version }}"
          version-type: "beta"
          loaders: |
            paper
            purpur
          game-versions: |
            1.19.4
            [1.20, 1.20.2]
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: Published Development Build
          description: |
            I have published a development build of Typewriter.
            Version: ${{ steps.vars.outputs.version }}
            [Download](https://modrinth.com/plugin/typewriter/version/${{ steps.publish.outputs.modrinth-version }})


